---
title: "Code to replicate figures in the paper"
author: "Santiago G. Medina-Muñoz"
date: "8/11/2020"
output:
  github_document: default
  html: True
---


Here, you can find some of the code that was used to generate the figures in the publication.

# Main Figures

## Figure 1

* [Figure 1A](paper-analysis/191005-EvaluateModelLearningCurve/06-plots.R)
* [Figure 1C](paper-analysis/191210-1nucOutOfFrameRepoterGopalData/01-plot.R)
* [Figure 1D](paper-analysis/191107-PredictReporterPairs/plot.R)

## Figure 2

* [Figure 2B](paper-analysis/191010-PredictStabilityInMZT/03_predictions_mzt.R)
* [Figure 2C](results/19-07-15-OptimalityStrongestPredictorOfMrnaStability/plot_results.R)


## Figure 3

* [Figure 3B-D](paper-analysis/191010-PredictStabilityInMZT/04_residualAnalusisMir430.R)
* [Figure 3E](paper-analysis/191012-Fig02SylamerAnalysis/04_plotM5cAndM6Amotifs.R)


## Figure 4

* [Figure 4A-B](results/19-08-19-OverlapFinal/02-mzt_overlap.R)
* [Figure 4C](results/19-08-19-OverlapFinal/04-mouse_overlap.R)
* [Figure 4D](results/19-08-19-OverlapFinal/03-overlap-mammalianMicroRNAs.R)
* [Figure 4E](results/19-08-19-OverlapFinal/05-plotMajoExperimentalResults.R)


## Figure 5

* [Figure 5A](paper-analysis/200305-MDIZER_mir430_OPtimality/analysis-DICER-boostrap.R)
* [Figure 5B](paper-analysis/200513-InteractionOptimalityMir430/02-interaction_fish.R)
* [Figure 5C](paper-analysis/200608-InteractionOptimalityMirArielome/200724-Analysis/02-InteractionBoostrap.R)


## Figure 6

* [Figure 6A](results/19-08-28-Fig04EvoAnalysis/03-plot_optimality_levels_in_miR430_targets.R)
* [Figure 6B](results/19-08-28-Fig04EvoAnalysis/04-model_of_mir430_enrichment.R)
* [Figures 6C-E](results/19-08-28-Fig04EvoAnalysis/conservation-analysis-ortologs.R)


# Supplemental Figures

## Supplemental Figure 1

* [Supplemental Figure 1B-D](results/19-01-10-EDA-RNA-time-course/01-EDA-time-course.Rmd)
* [Supplemental Figure 1E-F](results/19-01-11-GetDecayRateFromTimeCourse/plot_examples_paper.R)

## Supplemental Figure 2

* [Supplemental Figure 2B](paper-analysis/200715-EvaluationPositionPrediction/03-models.R)

## Supplemental Figure 3

* [Supplemental Figure 3A-B](paper-analysis/191005-EvaluateModelLearningCurve/02-PlotLearningCurve.R)
* [Supplemental Figure 3C](paper-analysis/191005-EvaluateModelLearningCurve/06-plots.R)
* [Supplemental Figure 3D](paper-analysis/200701-AddTimePoints/02-PredictionsOverTime.R)

## Supplemental Figure 4

* [Supplemental Figure 4B-D](results/19-09-03-Sup3_PLSanalysis/pls_data_viz.R)

## Supplemental Figure 5

* [Supplemental Figure S5A](paper-analysis/191010-PredictStabilityInMZT/06-PlotPaper.R)
* [Supplemental Figure S5B](paper-analysis/191012-Fig02SylamerAnalysis/05_elements_supplemental.R)
* [Supplemental Figure S5C](paper-analysis/191012-Fig02SylamerAnalysis/05_elements_supplemental.R)
* [Supplemental Figure S5D](paper-analysis/200702-SylamerAddTimePoints/scripts/03-make-plot.R)
* [Supplemental Figure S5E](paper-analysis/200705-SylamerInCodingStopcodonAnd3utr/04-m6a-sites.R)

## Supplemental Figure 6

* [Supplemental Figure S6A](paper-analysis/200701-AddTimePoints/03-MirOptimalityAdditive.R)
* [Supplemental Figure S6B](results/19-08-19-OverlapFinal/02-mzt-mir430-MA-genes.R)
* [Supplemental Figure S6C](results/19-08-19-OverlapFinal/05-plotMajoExperimentalResults.R)


## Supplemental Figure 7

* [Supplemental Figure 7E](paper-analysis/200608-InteractionOptimalityMirArielome/200724-Analysis/01-optimality.R)
