---
title: "Optimality Overlap With Other Pathways"
author: "Santiago Medina"
date: "March 17, 2019"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = F, message = F, warning = F, collapse = T,
  fig.path = "./figures/", dev = c("png", "pdf"),
  dpi=300,
  fig.height = 3,
  fig.width = 5
  )
library(tidyverse)
library(gridExtra)
library(ggthemes)
library(ggridges)

theme_set(theme_tufte(base_family = "Helvetica"))
```

### Overview

Do we see an overlap of codon optimality with other pathways? aka Do optimality affect MiR430 and m6A targets?Do we see an overlap of codon optimality with other pathwats?


I will define optimal/non-optimal genes in the following way:

+ top 1k lowest PLS1 (non-optimal)
+ top 1k highest PLS1 (optimal)


```{r getdata}
log2fc <- read_csv("../../data/19-02-05-FoldChangeData/data/log2FC_earlyVSlate_tidytimecourse.csv")

# load predictors
predictors <- read_csv("../19-02-24-OverlapPathwaysFig3/results_data/regulatory_pathways_matrix.csv") %>% 
  filter(is_maternal)

## get the true m6a targets

mym6alist <- read_csv("../19-02-26-M6A-targets/results_data/m6atargets_affected_in_mutant.csv")

predictors$m6A <- predictors$Gene_ID %in% mym6alist$gene_id

optimals <- tibble(
  optimal = arrange(predictors, -PLS1)$Gene_ID[1:1000],
  nonoptimal = arrange(predictors, PLS1)$Gene_ID[1:1000],
) %>% 
  gather(key = optimality, value = Gene_ID)

pathwasy <- 
  predictors %>% 
  select(Gene_ID, m6A, MiR430) %>% 
  left_join(optimals) %>% 
  replace_na(list(optimality = "neutral"))

dataf1 <- inner_join(log2fc, pathwasy) %>% 
  filter(time  > 3) %>% 
  mutate(time = paste0(time, " hrs"))
```


```{r 3ApathwayOverlap, fig.height=5, fig.width=3.5}
dataf1 %>% 
  filter(sample_condition == "wt_ribo") %>% 
  mutate(
    MiR430 = MiR430>0,
    optimality = factor(optimality, levels = c("optimal", "neutral", "nonoptimal"))
  ) %>% 
  select(log2FC, time, m6A, MiR430, optimality) %>% 
  gather(key = pathway, value = present, -time, -log2FC, -optimality) %>% 
  filter(present) %>% 
  ggplot(aes(y=log2FC, x=optimality, color=optimality)) +
  geom_rangeframe(color="black") +
  geom_boxplot(outlier.shape = NA) +
  facet_grid(time ~ pathway) +
  scale_color_manual(values = c("red", "#888888", "blue")) +
  coord_cartesian(ylim = c(-6.5, 1.5)) +
  labs(
    y = "log2 Fold Change (6hrs/2hrs)",
    x= NULL,
    title = "Optimality Overlaps with other Pathways"
  )
```


```{r 3bOverlapScatter, fig.height=7, fig.width=4}
# now we do a continious version of the sample plot using PLS1
dpb <- dataf1 %>% 
  mutate(MiR430 = MiR430 > 0) %>% 
  filter(sample_condition == "wt_ribo") %>% 
  inner_join(select(predictors, Gene_ID, PLS1)) %>% 
  mutate(
    onlym6a = m6A & !MiR430,
    onlyMiR430 = !m6A & MiR430,
    m6a_and_MiR430 = m6A & MiR430,
    no_regulation = !m6A & !MiR430
  ) %>% 
  select(Gene_ID, log2FC, time, PLS1:no_regulation) %>% 
  gather(key = "pathway", value = "present", -time, -log2FC, -Gene_ID, -PLS1) %>% 
  filter(present)


dpb %>% 
  filter(time > 4) %>% 
  mutate(
    pathway = factor(pathway, levels = c("no_regulation", "onlyMiR430", "onlym6a", "m6a_and_MiR430"))
  ) %>% 
  ggplot(aes(x=PLS1, y=log2FC)) +
  geom_point(color = "grey", size = .25) +
  geom_smooth(method = "lm", color = 'black', size = 1/2) +
  ggpubr::stat_cor(size = 2) +
  facet_grid(time~pathway) +
  labs(
    x = "codon optimality (PLS1)",
    y = "log2 6hrs / 2 hrs"
  ) +
  geom_rangeframe(color = "black", alpha = 1/3)
``` 


### Do the plot focusing only in MiR-430 targets

```{r mir430MA, fig.height=7, fig.width=4}
# see the readme file in that folder for a description of the data
mir430codes <- read_csv("../../data/19-01-17-EMBO2016DATA/datasets/Groups/mir430_genes_targets.csv") %>% 
  rename(Gene_ID = gene_id)
optimality <- 
  select(predictors, Gene_ID, PLS1, is_maternal)


mir430codes <- 
  mir430codes %>% 
  right_join(optimality) %>% 
  replace_na(list(kmer_type = "no target", MicroArray = "No"))

dta_plot <- inner_join(log2fc, mir430codes) %>% 
  filter(is_maternal, sample_condition == "wt_ribo") %>% 
  mutate(time = paste0(time, " hrs"))

dta_plot %>% 
  mutate(
    MicroArray = factor(MicroArray, levels = c("No", "Ma", "Ma78"))
  ) %>% 
  filter(time > 4) %>% 
  ggplot(aes(x=PLS1, y=log2FC, color=MicroArray)) +
  geom_point(size = .25, alpha=1/2) +
  geom_rangeframe(color="black") +
  ggpubr::stat_cor(color="black", size = 2) +
  facet_grid(time~MicroArray) +
  geom_smooth(method = "lm") +
  labs(
    title="MiR-430 MA",
    x = "codon optimality (PLS1)"
  )
```


```{r MiR430KmerOverlaps, fig.height=7, fig.width=4}
dta_plot %>% 
  mutate(
    kmer_type = factor(kmer_type, levels = c('no target', "6-mer", '7-mer', '8-mer', 'm-mer'))
  ) %>% 
  filter(time > 4) %>% 
  ggplot(aes(x=PLS1, y=log2FC)) +
  geom_point(color = "grey", size = .25, alpha=1/2) +
  geom_rangeframe() +
  ggpubr::stat_cor(color="black", size = 2) +
  facet_grid(time~kmer_type) +
  geom_smooth(method = "lm") +
  labs(
    x = "codon optimality (PLS1)",
    y = "log2 X hrs / 2 hrs"
  )
```


