---
title: "Optimizing mRNA stability by codon optimality"
author: "Santiago Medina"
date: "5/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = F, message = F, warning = F, collapse = T,
  fig.path = "./figures/", dev = c("png", "pdf"),
  dpi=300,
  fig.height = 3,
  fig.width = 5
  )
library(tidyverse)
library(ggthemes)
library(gridExtra)
theme_set(theme_tufte(base_family = 'Helvetica'))
```

## Overview

TODO: description

## Approach

## Results

```{r neutraloptimized ,fig.height=3, fig.width=5}
results <- read_csv("results_data/search.csv")
```

## Results Across Species

```{r optimized, fig.height=12, fig.width=12}
dta1 <- results %>% 
  mutate(gene = str_replace(gene, "(neutral |stable |unstable )", "")) %>% 
  select(-sequences, -fitness) %>% 
  gather(key = condition, value = fitness, -gene, -optimization, -iteration)


startingvals <- dta1 %>% 
  filter(iteration == 0) %>% 
  group_by(gene, condition) %>% 
  summarise(start_fitness = median(fitness))


maximals <- 
  dta1 %>% 
  group_by(condition, gene, iteration) %>% 
  summarise(
    min_opt = min(fitness),
    max_opt = max(fitness)
  )


dta1 %>% 
  ggplot(aes(x=iteration, y=fitness, color=fitness)) +
  geom_point(position = 'jitter', shape='.') +
  geom_hline(yintercept = 0, linetype=3) +
  geom_point(
    data = startingvals,
    aes(x=.5, y=start_fitness),
    color = "black",
    shape=16,
    size=3
  ) +
  geom_line(data = maximals, aes(x=iteration, y=min_opt), color="black", size=1/7) +
  geom_line(data = maximals, aes(x=iteration, y=max_opt), color="black", size=1/7) +
  #scale_color_gradient2(low = 'darkblue', high = 'firebrick2', mid = 'grey99', midpoint = 0) +
  scale_color_viridis_c("predited\nmRNA stability", option = "C") +
  geom_rangeframe(color="black") +
  facet_grid(condition ~ gene) +
  scale_x_continuous(breaks = c(1, 100, 200)) +
  coord_cartesian(ylim = c(-2.5, 2)) +
  labs(
    title = "genetic algorithm search"
  )

```


## Silent Reporter Sequences

```{r silent_reprs, fig.height=5, fig.width=5}
silent_reps <- read_csv("results_data/silent_reporters_seqs.csv")
silent_reps_opt_path <- read_csv("results_data/silentReporter_optimization_path.csv")


qs_optimization <- 
  silent_reps %>% 
  filter(str_detect(id_seq, "opt")) %>% 
  separate(id_seq, into = c("nothing", "p_optimal")) %>% 
  mutate(p_optimal = as.numeric(p_optimal))

methods_optimization <- 
  silent_reps %>% 
  filter(!str_detect(id_seq, "opt"))
  
p_rep <- silent_reps_opt_path %>% 
  ggplot(aes(x=iteration, y=fitness)) +
  geom_line(aes(group = optimization), color = "grey") +
  geom_point(
    data = qs_optimization,
    aes(x = 5, y = predicted_stability_human293t, color=p_optimal),
    size = 3, shape = 16, alpha=.9
  ) +
  scale_color_gradient2(low = "blue", high = "red", midpoint = 55) +
  geom_point(
    data = methods_optimization,
    aes(x = 10, y = predicted_stability_human293t),
    shape = 16, alpha=.9
  ) +
  ggrepel::geom_text_repel(
    data = methods_optimization,
    aes(x = 10, y = predicted_stability_human293t, label = id_seq)
  ) +
  theme(legend.position = "none") +
  scale_x_log10() +
  labs(
    x = "iteration",
    y = "predicted mRNA stability",
    title = "Optimization Silent Reporters",
    subtitle = "optimized for human 293t cells"
  )
```

## eGFP optimization

```{r opt_gfp_silent_reporters, fig.height=4, fig.width=4}
gfp_search <- read_csv("results_data/eGFP_optimization_path.csv")
gfp_seqs <- read_csv("results_data/gfp_sequences_predictions.csv")

p_gfp <- gfp_search %>% 
  ggplot(aes(x=iteration, y=`human | RPE | endogenous`)) +
  geom_line(aes(group = optimization), color = "grey") +
  geom_point(
    data = gfp_seqs,
    aes(x = 5, y = predicted_stability_human293t),
    shape = 16, alpha=.9
  ) +
  ggrepel::geom_text_repel(
    data = gfp_seqs,
    aes(x = 5, y = predicted_stability_human293t, label = seq_id)
  ) +
  scale_x_log10() +
  labs(
    x = "iteration",
    y = "predicted mRNA stability",
    title = "Optimization GFP",
    subtitle = "optimized for fish MZT"
  ) +
  coord_cartesian(ylim = c(-3, 3))


grid.arrange(p_gfp, p_rep, ncol=2)
```

### distribution of endogenous genes

```{r endoDistriRPEcells, fig.width=2, heigth=3}
decay_rate <- read_csv("../19-04-30-PredictiveModelDecayAllSpecies/19-04-30-EDA/results_data/training_set.csv") %>% 
  filter(specie == "human", cell_type == "293t")

decay_rate %>% 
  ggplot(aes(x=decay_rate)) +
  geom_histogram(bins = 50, color="white", fill="grey") +
  coord_cartesian(xlim = c(-3, 3)) +
  labs(
    title = "Distribution mRNA stability endogenous genes"
  ) +
  coord_flip()

```

