SAMPLES = ["AG01305.1", "AG01306.1", "AG01307.1", "AG01297.1", "AG01300.1", "AG01301.1"]


rule filter_by_seqlen:
    input:
        "../../../data/19-03-23-Arielome/processed_arielome_data/{sample}_premature_stop.csv"
    output:
    	"data/{sample}_seqs.csv"
    message:
        "Filtering short sequences {input}"
    shell:
	# you need to escape awk character { with {{
        """awk -F "," 'NR==1{{print;next}} length($2) >= 350 {{print}}' {input} | awk -F "," 'NR==1{{print;next}} length($3) >= 150 {{print}}' > {output}"""


rule add_optimality:
    input:
        "data/{sample}_seqs.csv"
    output:
    	"data/{sample}_optimality_mir.csv"
    message:
        "adding optimality and miR-430 presence to arielome seqs"
    script:
        "add-optimality.R"


rule gatherarielome:
    input:
        ari=expand("data/{sample}_optimality_mir.csv", sample=SAMPLES),
	metadata="../../../data/19-03-23-Arielome/Arielome/metadata.csv"
    output:
        "data/arielome_opt_mir.csv"
    script:
    	"gather_arielome.R"

