---
title: "plot figures 1"
author: "Santiago Medina"
date: "6/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = F, message = F, warning = F, collapse = T,
  fig.path = "./figures/", dev = c("png", "pdf"),
  dpi=300,
  fig.height = 3,
  fig.width = 5
  )
library(tidyverse)
library(ggthemes)


theme_set(theme_tufte(base_family = "Helvetica"))
```

## figure 1

scatter plot predictions in test data


```{r test_data_gbm_predictions, fig.height=3, fig.width=4}
predictions <- read_csv("../../../results/19-04-30-PredictiveModelDecayAllSpecies/19-05-01-TrainModels/results_data/val_gbm.csv")

predictions %>% 
  ggplot(aes(x=predicted, y=observed)) +
  geom_hex(bins=50) +
  geom_abline(linetype=2) +
  ggpubr::stat_cor(size=3) +
  scale_x_continuous(breaks = c(-2, -1, 0, 1, 2)) +
  scale_fill_viridis_c(option = "A") +
  scale_y_continuous(breaks = c(-2, -1, 0, 1, 2)) +
  labs(
    title = "Gradient Boosting Regressor",
    subtitle = str_c("test data n = ", nrow(predictions))
  )
```
 open the plot by specie
 
```{r predsdictions_by_specie, fig.height=2, fig.width=12}

predictions %>% 
  mutate(id = paste(specie, cell_type, sep = " | ")) %>% 
  ggplot(aes(x = predicted, y = observed)) +
  geom_point(shape=16, alpha=3/5, size = 1) +
  geom_abline(linetype=3) +
  ggpubr::stat_cor(size = 2.5) +
  facet_grid(~id) +
  labs(
    title = "Test Data Predictions"
  )

```

 
 I will show human RPE, mouse and fish.
 
```{r preds_by_specie, fig.height=2, fig.width=4}
preds_sub <- 
  predictions %>% 
  mutate(
    id = paste(specie, cell_type, datatype, sep = " | ")
  ) %>% 
  filter(id %in% c("fish | embryo mzt | aamanitin polya", "human | RPE | endogenous"))


preds_sub %>% 
  ggplot(aes(x=predicted, y=observed)) +
  geom_point(shape=16, alpha=1/2, size=1) +
  geom_abline(linetype=2) +
  ggpubr::stat_cor(size=2) +
  scale_x_continuous(breaks = c(-2, -1, 0, 1, 2)) +
  scale_fill_viridis_c(option = "A") +
  scale_y_continuous(breaks = c(-2, -1, 0, 1, 2)) +
  facet_grid(~id) +
  theme(strip.text.x = element_text(size = 6))

```
 
now plot the reporters predictions

***

## reporters validations

```{r reporters_pred, fig.height=2, fig.width=4}
dta <- read_csv("../../../results/19-04-30-PredictiveModelDecayAllSpecies/19-05-01-TrainModels/results_data/reporters_pr") %>% 
  mutate(id = paste(specie, cell_type, datatype, sep = " | ")) %>% 
  filter(id %in% c("fish | embryo mzt | aamanitin polya", "human | RPE | endogenous"))

reporters <- 
  dta %>% 
  filter(str_detect(gene_id, "\\|")) %>% 
  separate(gene_id, into = c("reporter_name", "optimality"), sep = "\\|")


# add random coodinates for plot
reporters <- 
  tibble(
    reporter_name = unique(reporters$reporter_name),
    positin_y = c(0.05, 0.3, 0.6, .8)
  ) %>% 
  inner_join(reporters)

# add a distance (aka fold change)
reporters <- 
  reporters %>% 
  spread(key = optimality, value = predicted) %>% 
  mutate(diff = optimal - `non-optimal`) %>% 
  gather(key = optimality, value = predicted,
         -reporter_name, -positin_y, -cell_type, -datatype, -specie,
         -observed, -id, -diff)

# get the reporter name to add as label just to one facet

repname <- reporters %>% 
  filter(
    id == "fish | embryo mzt | aamanitin polya",
    optimality == "optimal"
  )


dta %>% 
  ggplot(aes(predicted)) +
  geom_density(fill="grey", color=NA, alpha=1/2) +
  geom_line(
    data = reporters,
    aes(
      x = predicted,
      y = positin_y,
      group = reporter_name
    ),
    color = "black",
    size = 1/5
  ) +
  geom_point(
    data = reporters,
    aes(
      x = predicted,
      y = positin_y,
      color = optimality
    ),
    shape = 16,
    alpha = .75
  ) +
  geom_text(
    data = repname,
    aes(x=predicted + 0.6, y=positin_y, label=reporter_name),
    size = 1.8
  ) +
  scale_color_manual(values = c("blue", "red")) +
  facet_wrap(id ~ .) +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    legend.position = "none"
  ) +
  labs(
    y = NULL,
    x = "predicted mRNA stability\n(distribution of test data shown in background)",
    title = "Reporter Sequences"
  ) +
  theme(strip.text.x = element_text(size = 6))
```


***

## Feature importance

feature importance was estimated with the `iml` package as shown in the introduction manual.

```{r importance, fig.height=2.5, fig.width=4.5}
importance <- read_csv("../../../results/19-04-30-PredictiveModelDecayAllSpecies/19-05-01-TrainModels/results_data/feature_importance.csv")

# plot top k feature

effects_lm <- 
  read_csv("../../../results/19-04-30-PredictiveModelDecayAllSpecies/19-05-01-TrainModels/results_data/feature_effects_linearModel.csv") %>% 
  rename(feature = term)


inner_join(importance, effects_lm) %>% 
  arrange(-importance) %>% 
  slice(1:30) %>% 
  ggplot(aes(x = reorder(feature, -importance), y = importance, color = estimate > 0)) +
  geom_point(shape=16, alpha=.7) +
  scale_color_manual(values = c("blue", "red")) +
  labs(
    x = "feature",
    title = "top predictive features"
  ) +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    legend.position = "none"
  )
```

partial effects

```{r ale_effects, fig.height=5, fig.width=6}
effects <- read_csv("../../../results/19-04-30-PredictiveModelDecayAllSpecies/19-05-01-TrainModels/results_data/feature_effects.csv")

effects %>% 
  filter(x < 50, feature != "cdslenlog") %>% 
  ggplot(aes(x=x, y=.ale, color=.ale)) +
  facet_wrap(~feature, scales = "free_x") +
  geom_hline(yintercept = 0, linetype=3, color="grey") +
  geom_line() +
  geom_rangeframe(color="black", alpha = 0.8, size=1/2, sides = "l ") +
  scale_color_viridis_c() +
  theme(legend.position = "none") +
  labs(
    y = "ALE",
    title ="Accumulated local effects for top features",
    x = "feature value range"
  )

```


