---
title: "GFPs optimization analysis"
author: "Santiago Medina"
date: "8/13/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = F, message = F, warning = F, collapse = T,
  fig.path = "./figures/", dev = c("png", "pdf"),
  dpi=300,
  fig.height = 3,
  fig.width = 5
  )
library(tidyverse)
library(ggthemes)
library(scales)
library(ggforce)
theme_set(theme_tufte(base_family = 'Helvetica'))
```


## Load the data sets


```{r gfps, fig.height=2.5, fig.width=3.5}
# predicted stability
gfps <- read_csv("results_data/gfps_predictions_uncertanty.csv")

experiment <- readxl::read_excel("../19-07-29-ExperimentalResultsOptimizationGfpMajo/results_data/SecondQuantificationFinalGFPs.xlsx", col_names = c("sequence", "intensity"))

results <- 
  experiment %>% 
  filter(intensity != "err") %>%
  mutate(
    seq_id = str_replace(sequence, "GFP", ""),
    seq_id = str_c(seq_id, "GFP"),
    intensity = as.numeric(intensity)
  )

## get the median values


gfps_res <- 
  results %>% 
  group_by(seq_id) %>% 
  summarise(med_Int = median(intensity)) %>% 
  inner_join(gfps)

# merge to plot points
tmp <- inner_join(gfps, results) %>% 
  group_by(seq_id) %>% 
  mutate(med_Int = median(intensity))


gfps_res %>% 
  ggplot(aes(x=predictions, y=med_Int, color=log10(med_Int))) +
  ggrepel::geom_text_repel(aes(label=seq_id), color="black") +
  geom_errorbarh(aes(xmin=ci_l, xmax=ci_u), height=0) +
  geom_point(data = tmp, aes(x=predictions, y=intensity), alpha=1/3, shape=16) +
  scale_color_viridis_c() +
  scale_y_log10() +
  labs(
    x = "predicted mRNA stability",
    y = "Intensity GFP/mCherry\nlog10"
  ) +
  theme(legend.position = "none")
```

```{r majoRes, fig.height=3.5, fig.width=4}

datum <- 
  inner_join(gfps, results)

datum %>% 
  ggplot(aes(x=predictions, y=intensity, group=predictions, color=log10(intensity))) +
  geom_sina(alpha=.9, shape=16) +
  geom_mark_rect(aes(label=sequence), label.family =  "Helvetica", size =1/5, label.fill=NA, con.size = 1/7, label.fontsize = 5, expand = unit("3", "mm") ) +
  scale_color_viridis_c(option = "D") +
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x))) +
  annotation_logticks(sides = "l") +
  theme(legend.position = "none", axis.ticks.x = element_blank()) +
  labs(
    y = "intensity GFP/mCherry",
    x = "predicted mRNA stability"
  )


```

Obtain p values for the paper results section.

```{r}
# compare neutral GFP vs destabalized GFP
# we take the log10 of the intensity

results <- mutate(results, log10_intensity = log10(intensity))
    
results_neutral <- filter(results, sequence == "neutral")
results_infima <- filter(results, sequence == "infima")
results_egfp <- filter(results, sequence == "eGFP")
t.test(results_neutral$log10_intensity, results_infima$log10_intensity)
t.test(results_egfp$log10_intensity, results_neutral$log10_intensity)
```



## GFP search path

I plot the search path of the GFP

```{r search_path, fig.height=2.5, fig.width=3.5}
search_path <- read_csv("../19-05-23-ProteinOptimization/results_data/eGFP_optimization_path.csv")

search_path %>% 
  select(iteration, `human | RPE | endogenous`, optimization) %>% 
  rename(fitness = `human | RPE | endogenous`) ->
  search_path

search_path %>% 
  group_by(optimization, iteration) %>% 
  filter(abs(fitness) == max(abs(fitness))) %>% 
  ungroup() %>% 
  ggplot(aes(x=iteration + 1, y=fitness, group=optimization)) +
  geom_line() +
  scale_x_sqrt(breaks = c(10, 20, 50, 100, 200, 300)) +
  labs(
    x = "iteration",
    y = "predicted mRNA stability"
  ) +
  coord_cartesian(xlim = c(1, 300))
  
```


## correlation predicted stability and intensity fro sininimous reporters

```{r}
dtum <- read_csv("../19-05-23-ProteinOptimization/results_data/predict_silent_reporters.csv")

cor.test(dtum$predicted_stability, dtum$protein)
```

